[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/linux-backend",
    "crates/windows-backend",
    "crates/app",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/koinkafasi/yazi"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
